context:
  version: 1.6.3

package:
  name: jsonlint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/jsonlint/-/jsonlint-${{ version }}.tgz
  sha256: 987f42f0754b7bc0c84967b81fc2b4db0ed2ebe2117ccc5a5faa59e462447723

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - jsonlint --help

about:
  license: MIT
  license_file:
    - README.md
    - third-party-licenses.txt
  summary: JSON parser and validator with a CLI
  homepage: https://github.com/zaach/jsonlint
  repository: https://github.com/zaach/jsonlint

extra:
  recipe-maintainers:
    - danielnachun
